[package]
name = "hybrid_kv_store"
version = "0.1.0"
authors = ["jameslennon <jameslennon321@gmail.com>"]

[dependencies]
byteorder = "1.2.7"
rand = "0.6.5"
# bencher = "0.1.5"
criterion = "0.2.11"

[[bench]]
path = "src/benches.rs"
name = "benches"
harness = false
